"""检查模型 vs 数据库结构

Revision ID: 65d66846d870
Revises: 
Create Date: 2026-07-26 18:38:48.387407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d66846d870'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('images', sa.Column('tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'tags')
    op.drop_column('images', 'category')
    # ### end Alembic commands ###
